import fs from 'node:fs';
import path from 'node:path';
const ROOT=process.cwd(), SRC=path.join(ROOT,'src'), OUT=path.join(ROOT,'dist');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmtDate=s=>{if(!s)return'';const d=new Date(s+'T00:00:00');return new Intl.DateTimeFormat('cs-CZ').format(d)};
const md=s=>esc(s||'').split(/\n\s*\n/).map(p=>`<p>${p.replace(/\n/g,'<br>')}</p>`).join('');
const copy=(a,b)=>{fs.mkdirSync(path.dirname(b),{recursive:true});fs.cpSync(a,b,{recursive:true})};
function layout(title,body){return `<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} – Jaroslav Holeček</title><meta name="description" content="Překlady, digitalizace a elektronické knihy Jaroslava Holečka"><link rel="stylesheet" href="/assets/site.css"></head><body><header><div class="wrap brand"><div><h1>Jaroslav Holeček</h1><p>Překlady, digitalizace a elektronické knihy</p></div><div class="mark">☼</div></div></header><nav><div class="wrap"><a href="/">Úvod</a><a href="/kategorie/buddhismus/">Buddhismus</a><a href="/kategorie/hinduismus/">Hinduismus</a><a href="/kategorie/ramakrisna/">Rámakrišna</a><a href="/kategorie/taoismus/">Taoismus</a><a href="/kategorie/astrologie/">Astrologie</a><a href="/kategorie/digitalizace/">Digitalizace<a href="/informace/">Informace</a><a href="/admin/">Administrace</a></div></nav><main>${body}</main><footer><div class="wrap"><span>© ${new Date().getFullYear()} Jaroslav Holeček</span><span>Překlady · digitalizace · e-knihy</span></div></footer></body></html>`}
function card(b){return `<article class="card"><a class="cover" href="/l/${esc(b.slug)}/">${b.cover?`<img loading="lazy" src="${esc(b.cover)}" alt="Obálka: ${esc(b.title)}">`:''}</a><div class="card-body"><h3>${esc(b.title)}</h3><div class="meta">${fmtDate(b.date)}${b.pages?` · ${esc(b.pages)} stran`:''}</div>${b.author?`<div class="meta">${esc(b.author)}</div>`:''}<a class="more" href="/l/${esc(b.slug)}/">Více informací →</a></div></article>`}
function write(rel,html){const f=path.join(OUT,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,html)}
function build(){fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT,{recursive:true});copy(path.join(SRC,'assets'),path.join(OUT,'assets'));copy(path.join(SRC,'admin'),path.join(OUT,'admin'));if(fs.existsSync(path.join(SRC,'media')))copy(path.join(SRC,'media'),path.join(OUT,'media'));
 const infoFile=path.join(SRC,'content','pages','informace.json');
 if(fs.existsSync(infoFile)){
   const info=JSON.parse(fs.readFileSync(infoFile,'utf8'));
   const infoBody=`<div class="wrap"><div class="page-head"><div class="crumbs"><a href="/">Úvod</a> › Informace</div><h2>${esc(info.title||'Informace')}</h2></div><section><div class="info-profile">${info.photo?`<div class="info-photo"><img src="${esc(info.photo)}" alt="Jaroslav Holeček"></div>`:''}<div class="annotation">${info.intro?`<p><strong>${esc(info.intro)}</strong></p>`:''}${md(info.body)}</div></div></section></div>`;
   write('informace/index.html',layout(info.title||'Informace',infoBody));
 }
                 const dir=path.join(SRC,'content','books');const books=fs.readdirSync(dir).filter(x=>x.endsWith('.json')).map(x=>JSON.parse(fs.readFileSync(path.join(dir,x),'utf8'))).sort((a,b)=>String(b.date).localeCompare(String(a.date)));
 const newest=books.slice(0,9);const cats=['Buddhismus','Hinduismus','Rámakrišna','Taoismus','Astrologie','Digitalizace'];
 const home=`<div class="hero"><div class="wrap"><h2>Elektronické knihy</h2><p>Informace o překladech, digitalizacích a e-knihách z oblasti buddhismu, hinduismu, taoismu, Rámakrišny a astrologie.</p></div></div><section><div class="wrap"><div class="section-title"><h2>Nejnovější publikace</h2></div><div class="grid">${newest.map(card).join('')}</div></div></section><section style="background:#efe5d3"><div class="wrap"><div class="section-title"><h2>Hlavní oblasti</h2></div><div class="categories">${cats.map(c=>`<div class="cat"><h3>${c}</h3><p>${books.filter(b=>b.category===c).length} položek v katalogu.</p><a href="/kategorie/${slugify(c)}/">Zobrazit →</a></div>`).join('')}</div></div></section>`;write('index.html',layout('Úvod',home));
 for(const c of cats){const list=books.filter(b=>b.category===c);const body=`<div class="wrap"><div class="page-head"><div class="crumbs"><a href="/">Úvod</a> › ${esc(c)}</div><h2>${esc(c)}</h2><p>${list.length} publikací.</p></div><section><div class="grid">${list.map(card).join('')}</div></section></div>`;write(`kategorie/${slugify(c)}/index.html`,layout(c,body));}
 for(const b of books){const buttons=[['pdf','PDF'],['epub','EPUB'],['mobi','MOBI']].map(([k,l])=>`<a class="btn ${k} ${b[k]?'':'disabled'}" ${b[k]?`href="${esc(b[k])}" target="_blank" rel="noopener"`:'aria-disabled="true"'}>${l}${b[k]?' (Webshare)':''}</a>`).join('');const body=`<div class="wrap"><div class="detail"><div><div class="crumbs"><a href="/">Úvod</a> › <a href="/kategorie/${slugify(b.category)}/">${esc(b.category)}</a> › ${esc(b.title)}</div><div class="detail-cover">${b.cover?`<img src="${esc(b.cover)}" alt="Obálka: ${esc(b.title)}">`:''}</div></div><div><h1>${esc(b.title)}</h1><dl class="facts">${b.author?`<dt>Autor</dt><dd>${esc(b.author)}</dd>`:''}<dt>Vydáno na webu</dt><dd>${fmtDate(b.date)}</dd>${b.pages?`<dt>Počet stran</dt><dd>${esc(b.pages)}</dd>`:''}${b.credits?`<dt>Úprava</dt><dd>${esc(b.credits)}</dd>`:''}<dt>Kategorie</dt><dd>${esc(b.category)}</dd></dl><div class="buttons">${buttons}</div><div class="annotation"><h3>Anotace</h3>${b.summary?`<p><strong>${esc(b.summary)}</strong></p>`:''}${md(b.body)}</div></div></div></div>`;write(`l/${b.slug}/index.html`,layout(b.title,body));}
 console.log(`Built ${books.length} publications into ${OUT}`);
}
function slugify(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
build();
if(process.argv.includes('--watch')){console.log('Watching src/content/books ...');fs.watch(path.join(SRC,'content','books'),{recursive:true},()=>{try{build()}catch(e){console.error(e)}})}
